### ISSUE TITLE
 ModuleNotFoundError: No module named 'gdcm'

### ISSUE THREAD

**Issue by tanishq19** [Rakshith2597/Dicom-fileconverter#3]
C:\Users\hp\AppData\Local\Programs\Python\Python36\dicom-flask-uploader-master\dicom_flask_uploader>python app.py
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    from models import db, uploaded_dicoms, Dicom
  File "C:\Users\hp\AppData\Local\Programs\Python\Python36\dicom-flask-uploader-master\dicom_flask_uploader\models.py", line 3, in <module>
    import mudicom
  File "C:\Users\hp\AppData\Local\Programs\Python\Python36\lib\site-packages\mudicom\__init__.py", line 15, in <module>
    from .base import Dicom
  File "C:\Users\hp\AppData\Local\Programs\Python\Python36\lib\site-packages\mudicom\base.py", line 11, in <module>
    import gdcm
ModuleNotFoundError: No module named 'gdcm'

**Comment by Rakshith2597** [comment]
gdcm was missing in the requirements.txt file, This can be solved by either installing the module separately or installing all packages using the updated requirements.txt
